---
- name: Configure the FTP Server using vsftpd
  hosts: test
  tasks:
    - name: Install packages - vsftpd, firewalld
      ansible.builtin.dnf:
        name:
          - vsftpd
          - firewalld
          - ftp
        state: present

    - name: Enable service - vsftpd, firewalld
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - vsftpd
        - firewalld

    - name: Open the port for vsftpd service
      ansible.posix.firewalld:
        service: ftp
        permanent: true
        immediate: true
        state: enabled

    - name: Check the anonymous enable - /etc/vsftpd/vsftpd.conf
      ansible.builtin.lineinfile:
        path: /etc/vsftpd/vsftpd.conf
        regexp: '^anonymous_enable'
        line: 'anonymous_enable=NO'
      ignore_errors: yes
      notify: restart vsftpd

    - name: Check root access - /etc/vsftpd/ftpusers
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        regexp: '^root'
        line: '#root'
      ignore_errors: yes
      loop:
        - /etc/vsftpd/ftpusers
        - /etc/vsftpd/user_list
      notify: restart vsftpd

  handlers:
    - name: restart vsftpd
      ansible.builtin.systemd:
        name: vsftpd
        state: restarted
