---
- name: /etc/myhosts file create
  hosts: dev
  tasks:
    - name: Create /etc/myhosts file Using Template
      ansible.builtin.template:
        src: hosts.j2
        dest: /etc/myhosts
        owner: root
        group: root
        mode: '0644'
